// Korean coverage universe + global peers for the 수급 / 밸류에이션 tabs.
export const KR = [
  { code: '035420', mkt: 'KS', name: 'NAVER', sector: '인터넷' },
  { code: '035720', mkt: 'KS', name: '카카오', sector: '인터넷' },
  { code: '259960', mkt: 'KS', name: '크래프톤', sector: '게임' },
  { code: '036570', mkt: 'KS', name: '엔씨소프트', sector: '게임' },
  { code: '251270', mkt: 'KS', name: '넷마블', sector: '게임' },
  { code: '293490', mkt: 'KQ', name: '카카오게임즈', sector: '게임' },
  { code: '263750', mkt: 'KQ', name: '펄어비스', sector: '게임' },
  { code: '462870', mkt: 'KS', name: '시프트업', sector: '게임' },
  { code: '078340', mkt: 'KQ', name: '컴투스', sector: '게임' },
  { code: '112040', mkt: 'KQ', name: '위메이드', sector: '게임' },
  { code: '095660', mkt: 'KQ', name: '네오위즈', sector: '게임' },
  { code: '181710', mkt: 'KS', name: 'NHN', sector: '인터넷' },
  { code: '194480', mkt: 'KQ', name: '데브시스터즈', sector: '게임' },
  { code: '192080', mkt: 'KS', name: '더블유게임즈', sector: '게임' },
  { code: '069080', mkt: 'KQ', name: '웹젠', sector: '게임' },
  { code: '018260', mkt: 'KS', name: '삼성에스디에스', sector: 'IT서비스' },
  { code: '064400', mkt: 'KS', name: 'LG CNS', sector: 'IT서비스' },
];
export const GLOBAL = [
  { sym: '0700.HK', name: 'Tencent', region: 'CN/HK', ccy: 'HKD' },
  { sym: '9999.HK', name: 'NetEase', region: 'CN/HK', ccy: 'HKD' },
  { sym: '7974.T', name: 'Nintendo', region: 'JP', ccy: 'JPY' },
  { sym: '3659.T', name: 'Nexon', region: 'JP', ccy: 'JPY' },
  { sym: '6758.T', name: 'Sony', region: 'JP', ccy: 'JPY' },
  { sym: '9697.T', name: 'Capcom', region: 'JP', ccy: 'JPY' },
  { sym: 'TTWO', name: 'Take-Two', region: 'US', ccy: 'USD' },
  { sym: 'RBLX', name: 'Roblox', region: 'US', ccy: 'USD' },
  { sym: 'U', name: 'Unity', region: 'US', ccy: 'USD' },
  { sym: 'APP', name: 'AppLovin', region: 'US', ccy: 'USD' },
  { sym: 'SE', name: 'Sea Ltd', region: 'US/SG', ccy: 'USD' },
  { sym: 'PLTK', name: 'Playtika', region: 'US', ccy: 'USD' },
  { sym: 'UBI.PA', name: 'Ubisoft', region: 'EU', ccy: 'EUR' },
  { sym: 'CDR.WA', name: 'CD Projekt', region: 'EU', ccy: 'PLN' },
];
// Steam apps for the CCU tracker (appid, display name, company)
export const STEAM_APPS = [
  { appid: 578080, name: 'PUBG: BATTLEGROUNDS', co: '크래프톤' },
  { appid: 2456740, name: 'inZOI', co: '크래프톤' },
  { appid: 1962700, name: 'Subnautica 2', co: '크래프톤' },
  { appid: 3393110, name: 'AION 2', co: '엔씨소프트' },
  { appid: 3321460, name: 'Crimson Desert', co: '펄어비스' },
  { appid: 582660, name: 'Black Desert', co: '펄어비스' },
  { appid: 3489700, name: 'Stellar Blade', co: '시프트업' },
  { appid: 1049590, name: 'Eternal Return', co: '님블뉴런(카카오게임즈)' },
  { appid: 1599340, name: 'Lost Ark', co: '스마일게이트' },
  { appid: 2074920, name: 'The First Descendant', co: '넥슨' },
  { appid: 1868140, name: 'DAVE THE DIVER', co: '넥슨(민트로켓)' },
  { appid: 3557620, name: 'Blue Archive', co: '넥슨게임즈' },
  { appid: 1973530, name: 'Limbus Company', co: '프로젝트문' },
  { appid: 1817190, name: 'Marvel Rivals', co: '넷이즈' },
  { appid: 2358720, name: 'Black Myth: Wukong', co: 'Game Science' },
];
